const ACTIONS = {
    FETCH_ALL_REQUEST: 'FETCH_ALL_COMMENT_REQUEST',
    FETCH_ALL_SUCCESS: 'FETCH_ALL_COMMENT_SUCCESS',
    FETCH_ALL_FAIL: 'FETCH_ALL_COMMENT_FAIL',

    CREATE_REQUEST: 'CREATE_COMMENT_REQUEST',
    CREATE_SUCCESS: 'CREATE_COMMENT_SUCCESS',
    CREATE_FAIL: 'CREATE_COMMENT_FAIL',
}
export default ACTIONS