const ACTIONS = {
    SEARCH_PARTNER_REQUEST: "SEARCH_PARTNER_REQUEST",
    SEARCH_PARTNER_SUCCESS: "SEARCH_PARTNER_SUCCESS",
    SEARCH_PARTNER_FAIL: "SEARCH_PARTNER_FAIL",
}

export default ACTIONS;